FROM amd64/maven as build-image

WORKDIR "/task"
COPY src src/
COPY pom.xml ./

RUN mvn -q clean package

FROM public.ecr.aws/awsguru/lambda-http-ric:latest as http-ric

FROM public.ecr.aws/lambda/java:8.al2

COPY --from=build-image /task/target/petstore-0.0.1-SNAPSHOT.jar /var/task/
COPY --from=http-ric /opt/bin/lambda-http-ric /opt/bin/

ENTRYPOINT ["/opt/bin/lambda-http-ric"]
# Command can be overwritten by providing a different command in the template directly.
CMD ["java", "-jar", "petstore-0.0.1-SNAPSHOT.jar"]
